[project]
name = "parallelism"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "tqdm>=4.67.1",
]
